name: 'dbt_bigquery_monitoring'
version: '1.0.0'
config-version: 2

profile: 'dbt_bigquery_monitoring'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  bigquery_database: "iloc-dbt-package-testing"
  bigquery_source_schema: "region-us.INFORMATION_SCHEMA"
  bigquery_target_tz: "UTC"
  bigquery_source_tz: "UTC"
  bigquery_on_demand_compute_pricing_per_tb: 5
